export default[
    {
    setup:"vfdvfdvbf",
    punchline:"kjcvnjfdkfd"
    },
    {
        setup:"vfdvfdvbf",
        punchline:"kjcvnjfdkfd"
        },
        {
            setup:"vfdvfdvbf",
            punchline:"kjcvnjfdkfd"
            },
            {
                setup:"vfdvfdvbf",
                punchline:"kjcvnjfdkfd"
                },
                {
                    setup:"vfdvfdvbf",
                    punchline:"kjcvnjfdkfd"
                    }
]